workflow:
  Robots:
    - class: KukaLBRIIWA
      id: 1
      location:
        node_id: 13
        graph_id: 7
        frame_name: neutral
      saved_frames:
  Materials:
    liquids:
      - name: water
        id: 145
        amount_stored: 400
        unit: ml
        density: 997 #g/l
        pump_id: pUmP1
        expiry_date: 2025-02-11
    solids:
      - name: sodium_chloride
        id: 345
        amount_stored: 10000
        dispense_method: quantos
        cartridge_id: cat1
        unit: mg
        expiry_date: 2025-02-11
  Stations:
    - class: ChemSpeedFlexStation
      id: 9
      location:
        node_id: 27
        graph_id: 7
      process_state_machine:
        type: ChemSpeedRackProcessingSm
        args:
          batch_mode: true
      parameters:
  name: chemspeed_test_workflow
  timestamp: 08/26/2021, 15:28:26
